Service Professions Overhaul
Persistent-SS13/PersistenceUnleashed pull request #23
Opened 2023-09-20 05:10 UTC by Crimsonerva

## Description of changes
The service sector of the game is currently very lacking. Sure, you can repeatedly grow and grind crops for biomass, but the diversity is low on this end. By implementing gameplay loops revolving around individualistic steps of cooking, raising livestock, making bartending actually interesting, etc, hopefully we can alleviate a lot of these issues.

This PR also introduces the concept of tailoring. Clothing quality should degrade over time, but that's not something I can feasibly do in my coding skills yet. For now, I've taken all clothing out of lathes to implement this new tailoring mechanic. In order to make clothing now, you must now print "frames" or "stencils" of different clothings. In order to complete these new stencils, a variety of gear is available from a new lathe: the tailoring bench. Much like an autolathe... except fabricates tailoring items. After applying tools to a stencil, you'll then be able to apply a corresponding material to complete the stencil and get the clothing you've just designed. In the future, I'd like things to have to get tailor fit, or at least have different sizes according to players, but once again, not feasible with my level of coding skills.

With the new cooking, instead of mashing everything inside of a microwave, you'll now be hand crafting ingredients for the most part. When it comes to adding toppings (like for pizza) or specialized flavors (cake), you'll include them in the microwave, depending on what it is. Here, hopefully using sprites, we can make it intuitive (and also via descriptions) on the next steps, and step away from requiring the codex in this sector. While the codex is a powerful tool, I want to make sure everything I can in the service sector is intuitive and can be either learned from trial and error, or through clues left behind in the game.

## Authorship
me, me, and all me!!
all new sprites made by me. all new code, too. except i learned how to make the code by mashing together old code.

**Hydroponics:**
- [x] Reorganize biogenerator
- [ ] Add custom names to the list (so bottles wont just show up as "bottle"
- [ ] Un-grayscale hydroponics (they cannot currently export; as the items are all created from datums)
- [ ] Re-organize existing plants and sprites

**Bartending:**
- [ ] Readjust all mixed drinks to be able to be made from scratch
- [ ] Make recipes a bit more unique, perhaps delayed, instead of instantly transforming
- [ ] Give mixed drinks export value on starter planet, and at least 2 beacons.

**Cooking:**
- [ ] Resprite all current food (thats not LRP, and remove LRP)
- [ ] Add new tools for food prep work (hamburger press, cookie cutter, mixing bowl, mixer, etc)
- [ ] Move all food (most) prep to hand-work, instead of using the microwave.
- [ ] Convert the microwave into a dual stove-oven so you don't have to keep baking cakes in the microwave
- [ ] Remove the cookers (candy machine, oven, etc) from the game and use new tools for prep work and creation
- [ ] Ensure all food has an actual crafting recipe
- [ ] Add MORE food

**Ranching:**
- [ ] Create new meals requiring butchering of livestock
- [ ] Change chicken limit (since they need constant maintenance anyways or will die)
- [ ] Make all livestock available via biogenerator (until we get lifecycles there's no reason to make them purchased by beacons)
- [ ] Make at least 1 beacon have some livestock exports.

**Tailoring:**
- [ ] add tailoring bench
- [ ] make stencils for all types of clothing (that isnt armor, at least, advanced)
- [ ] make stencils for clothing attachments
- [ ] make tools for tailoring bench
- [ ] make tools applicable on stencils
- [ ] make stencils actually turn into clothing

2023-09-20 05:38 UTC, Crimsonerva commented
fyi i accidentally removed area control boards in a commit and i couldnt readd them without it making another commit and i had no way to delete it, so. dont yell at me about it please!!

2023-09-21 22:23 UTC, Crimsonerva commented
an issue i noticed that seems unrelated is that corn is actually really evil and grows off of the tray, then sprouts tendrils and starts attacking you. i havent seen any reason it does this but just marking it down as an FYI

2023-09-21 23:11 UTC, Crimsonerva commented
a lot of this is old code which i found way easier to port; will have to port newer code to get up-to-date in the future

2023-09-22 04:47 UTC, out-of-phaze requested changes
NO NO NO NO NO
https://www.byond.com/docs/ref/index.html#/proc/clamp

2023-09-22 04:47 UTC, out-of-phaze commented on code/_macros.dm
> +#define CLAMP01(x) 		(Clamp(x, 0, 1))
NO
```suggestion
#define CLAMP01(x) 		(clamp(x, 0, 1))
```

2023-09-22 04:47 UTC, out-of-phaze commented on code/modules/fabrication/machines/_cooker.dm
> +			temp_scale = Clamp(1 - ((optimal_temp - temperature) / optimal_temp), 0, 1)
```suggestion
			temp_scale = clamp(1 - ((optimal_temp - temperature) / optimal_temp), 0, 1)
```

2023-09-22 04:47 UTC, out-of-phaze commented on code/modules/fabrication/machines/_cooker_output.dm
> +		scale = Clamp(scale, min_scale, max_scale)
```suggestion
		scale = clamp(scale, min_scale, max_scale)
```

2023-09-22 04:47 UTC, out-of-phaze commented on code/modules/fabrication/machines/stove.dm
> +				pan_overlay = image('icons/obj/cooking_machines.dmi', "skillet[Clamp(length(pans)+1, 1, 4)]")
```suggestion
				pan_overlay = image('icons/obj/cooking_machines.dmi', "skillet[clamp(length(pans)+1, 1, 4)]")
```

2023-09-22 04:47 UTC, out-of-phaze commented on code/modules/fabrication/machines/stove.dm
> +				pan_overlay = image('icons/obj/cooking_machines.dmi', "pan[Clamp(length(pans)+1, 1, 4)]")
```suggestion
				pan_overlay = image('icons/obj/cooking_machines.dmi', "pan[clamp(length(pans)+1, 1, 4)]")
```

2023-09-22 04:47 UTC, out-of-phaze commented on code/modules/fabrication/machines/stove.dm
> +				pan_overlay = image('icons/obj/cooking_machines.dmi', "pot[Clamp(length(pans)+1, 1, 4)]")
```suggestion
				pan_overlay = image('icons/obj/cooking_machines.dmi', "pot[clamp(length(pans)+1, 1, 4)]")
```

2023-09-22 04:47 UTC, out-of-phaze commented on code/_macros.dm
> +
NO NO NO NO NO
https://www.byond.com/docs/ref/index.html#/proc/clamp
```suggestion
```

2023-09-22 14:28 UTC, Crimsonerva commented
work atm. patched all the missing icons i could find and doesn't seem to break anything aside from part of the codex, which i can fix tonight

2023-09-23 00:06 UTC, merged